language: java

git:
  depth: false

addons:
  sonarcloud:
    organization: enniovisco
    token:
      secure: "VO4i8VmC8I7M1aVLCMD2s0oS6tPEdWEBbRvLBnNuxE5SqPfKva6sJulFf+tUDgqqdYXwz+pH4s8C8Q/+kyiuoz3JM2mDgOmCXehK+t8X5hYVlFsaIgE5gCfE2OAknfNRyEtJdng1BdeLpGdZPucRyLKP7TcIjO+f1wwt60UnH
sQN760g0HSZ6xipufuYhZoecPSvNtgqGBgxs5jcMkKFtjP/jj7qPCMrUDQo2KVsJ/npZZXV3oyshZ/E2Osqq9/02HxaeR5QiGmswsjJbtN/VSPmCW71vWloYSEvoAwWcM2G9+aoHHWrv639NLBLWK1tYt0mN2iBuWL1LddhtaIVelM34Ku+p
rNGKcX1QhaP80CffyVGcnuoxGBZMqb0gE/PtVb98Hw5Zk41y3EuRdjQ3NFyiUVIeSRgb4R+A9QbcyJ9JZoCoxB9ZG1w2WjQp+I72JSaz/oBnTLwt8lTRPUhKa1RiJyFg4daxzk3ItSXxPsLrHv9NWbcATYRaRKUOHjRLT+athaXeF9Qi/4Oa
+fVDDOMwNQY2FiJVDggq2qFE8XaVai1vQXb6WJWWucfWch3QbLFHOgqmJWU9hkj19dbXvirNlWIFPcPumxppLb5+pVHKljWuOJOuUWcoTyc3x0pkXk/dSGlQVVTw4vAIlzEYtGvQdsGbR/VEaLQkszmRNk="

script:
- "./gradlew sonarqube"
