/*
 * generated by Xtext 2.18.0.M3
 */
package eu.quanticol.moonlight.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MoonLightScriptRuntimeModule extends AbstractMoonLightScriptRuntimeModule {
}
