/*
 * generated by Xtext 2.18.0.M3
 */
package eu.quanticol.moonlight.xtext.ide


/**
 * Use this class to register ide components.
 */
class MoonLightScriptIdeModule extends AbstractMoonLightScriptIdeModule {
}
