# Building workflow for moonlight
on: [push, pull_request]
        
#release:
 # types: [created]

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
        
  coverage:
    name: Codecov coverage
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle check
        run: ./gradlew check
        
      - name: Codecov update
        uses: codecov/codecov-action@v1
        with:
          token: "e55b13c2-bff0-49c1-81e8-0fe254c2955e"
          #files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest 
    
    permissions: 
      contents: read
      packages: write 
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
