# Publish package to GitHub Packages
name: publish package
on:
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Publish Github Package with Gradle
        run: ./gradlew publish
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        run: gradle publish --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
