# Publish package to GitHub Packages
name: Publish on PyPi
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Build releasable python package
        run: ./gradlew :python:distribute

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pipx install poetry

      - name: Publishing setup
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        working-directory: ./python

      - name: Build & deploy package
        run: poetry publish --build
        working-directory: ./python
