# Publish package to GitHub Packages
name: publish on pypi
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build releasable python package
        run: ./gradlew release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move artifacts to python folder
        run: |
          mv engine/build/libs/engine-1.0-SNAPSHOT.jar python/src/moonlight/jar/engine.jar
          mv script/build/libs/script-1.0-SNAPSHOT.jar python/src/moonlight/jar/script.jar
        uses: canastro/copy-file-action@master
        with:
          source: "engine/build/libs/engine-1.0-SNAPSHOT.jar"
          target: "python/src/moonlight/jar/engine.jar"

      - name: Move artifacts to python folder
        uses: canastro/copy-file-action@master
        with:
          source: "script/build/libs/script-1.0-SNAPSHOT.jar"
          target: "python/src/moonlight/jar/script.jar"

      - run: cd python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pipx install poetry

      - name: Publishing setup
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build & deploy package
        run: poetry publish --build

#      - name: Publish a Python distribution to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
