/*
 * generated by Xtext 2.18.0.M3
 */
package eu.quanticol.moonlight.xtext.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class MoonLightScriptScopeProvider extends AbstractMoonLightScriptScopeProvider {

}
